--- # DataConfiguration - datagenerator2.yml
name: Test
databaseName: /home/uwe/development/datagenerator2/generateddata.duckdb
tableName: generateddata
fields:
  - name: random1
    type: randomstring
    options:
      minLength: 20
      maxLength: 20
  - name: random2
    type: randomlong
    options:
      minValue: -1000
      maxValue: 999
  - name: random3
    type: randomdouble
    options:
      minValue: 100
      maxValue: 5000
    transformations:
      - name: round
        parameters:
          - 3
      - name: negate
  - name: gender
    type: category
    values:
      - value: m
        weight: 40
      - value: f
        weight: 40
      - value: d
        weight: 20
    valuesFile: /home/uwe/development/datagenerator2/categories/gender.category
  - name: weekday
    type: category
    transformations:
      - name: encrypt
    values:
      - value: Saturday
        weight: 5
      - value: Sunday
        weight: 5
    valuesFile: /home/uwe/development/datagenerator2/categories/weekday.category
  - name: season
    type: category
    valuesFile: /home/uwe/development/datagenerator2/categories/season.category
    values:
      - value: Summer
        weight: 70
  - name: city
    type: category
    valuesFile: /home/uwe/development/datagenerator2/categories/city.category
  - name: number
    type: category
    valuesFile: /home/uwe/development/datagenerator2/categories/number.category
