--- # ProgramConfiguration - programconfiguration-test-01.yml
general:
  exportFilename: /tmp/csv_export.json
  exportType: json
  numberOfRowsToGenerate: 5000
  generatedRowsLogInterval: 1000
  rowNumberFieldName: rownumber
csvExport:
  delimiter: comma
  includeHeader: true
jsonExport:
  asArray: true
excelExport:
  format: gdal
  driver: xlsx