--- # ProgramConfiguration - programconfiguration-test-01.yml
exportFilename: /tmp/csv_export.json
exportType: json
numberOfRowsToGenerate: 5000
generatedRowsLogInterval: 1000
csvExport:
  delimiter: comma
  includeHeader: true
jsonExport:
  asArray: true
