--- # ProgramConfiguration - programconfiguration-test-01.yml
outputFilename: /home/uwe/development/datagenerator2/csv_export.csv
numberOfRowsToGenerate: 2500
csvExport:
  delimiter: "'"
  includeHeader: true
